maintainer       "YOUR_COMPANY_NAME"
maintainer_email "YOUR_EMAIL"
license          "All rights reserved"
description      "Installs/Configures vagrant_main"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.0.1"
depends          "apt"
depends          "build-essential"
depends          "git"
depends          "apache2"
depends          "mysql"
depends          "php"
depends          "composer"
depends          "phing"
depends          "php-box"
depends          "drush"
depends          "magento-toolbox"
depends          "nodejs"
depends          "npm"
depends          "python"
